### ISSUE TITLE
Error compiling on MBED online compiler

### ISSUE THREAD

**Issue by bsturgess** [janjongboom/at45-blockdevice#2]
Hello

Would love to use this lib but i get the following error when trying to compile on the mbed online compiler...

Error: Expression must be a pointer to a complete object type in "AT45BlockDevice.h", Line: 80, Col: 14

Any ideas of the solution with this compiler?

Thanks

Ben

**Comment by janjongboom** [comment]
Fixed in https://github.com/janjongboom/at45-blockdevice/pull/3
